# Generated by Django 5.2.4 on 2026-06-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_owner_memberships(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    GroupMembership = apps.get_model("groups", "GroupMembership")
    GroupMembership.objects.bulk_create(
        [
            GroupMembership(
                group_id=group.id,
                user_id=group.owner_id,
                role="owner",
                joined_at=group.created_at,
            )
            for group in Group.objects.all().iterator()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at', 'id'),
                'indexes': [models.Index(fields=['group', 'user', 'joined_at', 'left_at'], name='groups_grou_group_i_894147_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gt', models.F('joined_at')), _connector='OR'), name='membership_left_after_joined'), models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('group', 'user'), name='one_open_membership_per_group_user')],
            },
        ),
        migrations.RunPython(create_owner_memberships, migrations.RunPython.noop),
    ]
