# Generated by Django 5.2.4 on 2026-06-14 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('target_currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(1e-08)])),
                ('effective_date', models.DateField()),
                ('source', models.CharField(default='manual', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-effective_date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('source_currency', 'target_currency', 'effective_date', 'source'), name='unique_exchange_rate_source_day')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a three-letter ISO 4217 code.', regex='^[A-Z]{3}$')])),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact amounts'), ('percentage', 'Percentage'), ('shares', 'Shares')], max_length=12)),
                ('incurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.exchangerate')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-incurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('input_value', models.DecimalField(blank=True, decimal_places=4, help_text='Exact amount, percentage, or share count supplied by the user.', max_digits=14, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'status', 'incurred_at'], name='expenses_ex_group_i_bc6301_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='one_split_per_expense_user'),
        ),
    ]
