# Generated by Django 5.2.4 on 2026-06-14 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='expense_imports/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('needs_review', 'Needs review'), ('ready', 'Ready'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('issue_count', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('blocked', 'Blocked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='staged', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importsession')),
            ],
            options={
                'ordering': ('row_number',),
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_code', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('raw_value', models.TextField(blank=True)),
                ('proposed_action', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved action'), ('rejected', 'Rejected action'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importrow')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importsession')),
            ],
            options={
                'ordering': ('row_number', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='importsession',
            constraint=models.UniqueConstraint(fields=('group', 'checksum_sha256'), name='one_import_per_group_checksum'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('session', 'row_number'), name='unique_import_row_number'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['session', 'status', 'severity'], name='imports_imp_session_5a3e89_idx'),
        ),
    ]
